# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "add7504331733e92252623482056ef16"
name = "app next template"
application_url = "https://able-gore-imposed-buffer.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "matts-tech-test.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://able-gore-imposed-buffer.trycloudflare.com/auth/callback",
  "https://able-gore-imposed-buffer.trycloudflare.com/auth/shopify/callback",
  "https://able-gore-imposed-buffer.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
