# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "add7504331733e92252623482056ef16"
name = "app next template"
application_url = "https://bathroom-menu-described-aud.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "matts-tech-test.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://bathroom-menu-described-aud.trycloudflare.com/auth/callback",
  "https://bathroom-menu-described-aud.trycloudflare.com/auth/shopify/callback",
  "https://bathroom-menu-described-aud.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
